feature: add-controller
PanCakeOFF31/java-shareit pull request #3
Opened 2024-04-16 12:35 UTC by PanCakeOFF31

2024-04-16 18:40 UTC, z8q requested changes

2024-04-16 18:40 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item createItem(@Valid @RequestBody final Item item,
Тут в принимаемых аргументах тоже нужно использовать дто.
Возвращаемые значения тоже для всех методов надо на дто переделать.

dto – для работы в контроллерах и бизнес логики.
сущности – для хранения в базе, определения зависимостей между другими сущностями (больше информации появится в новой домашке про hibernate).

2024-04-16 18:40 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public User createUser(@Valid @RequestBody final User user) {
Тут такой же коммент про дто как в контроллере с Item-ами

2024-04-16 18:40 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/repository/UserInMemoryRepository.java
> +        return Optional.of(deletedUser);
можно посмотреть Optional.ofNullable, тогда блок if выше не будет нужен

2024-04-17 07:55 UTC, PanCakeOFF31 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item createItem(@Valid @RequestBody final Item item,
Теперь знаю когда и где Dto и Сущность соответственно

2024-04-17 18:04 UTC, z8q approved these changes

2024-04-17 18:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void emailValidation(final UserDto user) {
Можно попробовать упростить, объединить в один метод.
В аргументах принимать только email например, тогда подойдет как для User, так и для UserDto

2024-04-18 05:57 UTC, merged