feature: add-bookings
PanCakeOFF31/java-shareit pull request #4
Opened 2024-05-04 11:07 UTC by PanCakeOFF31

2024-05-05 11:36 UTC, z8q requested changes

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
В дипломе будет рекомендация не использовать equals и hashcode в сущностях хибернейта.
[здесь](https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/) и [здесь](https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/) можно почитать, какие проблемы могут возникать и в каких случаях можно использовать

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NotNull
Валидировать поля лучше силами дто. На сущностях оставить только функционал описания таблиц, зависимостей между таблицами и как подгружать зависимые сущности lazy,eager

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingResponseDto> getAllBookingByUser(@RequestHeader("X-Sharer-User-Id") final long bookerId,
Попробуй передать запрос в таком виде
```
curl --request GET \
  --url http://localhost:8080/bookings \
  --header 'X-Sharer-User-Id: '
```
Само название хедера указано в запросе, но для него нет значения.
Сейчас такой случай не обрабатывается.
Причем, если мы исползьуем в агрументах метода примитив - long bookerId, будет исключение MethodArgumentTypeMismatchException с сообщением
```
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: 
Failed to convert value of type 'java.lang.String' to required type 'long'; 
nested exception is java.lang.NumberFormatException: For input string: ""
```

Если в аргументах контроллера использовать обертку - Long bookerId, будет другое исключение и описание. Вероятно, более информативное
```
org.springframework.web.bind.MissingRequestHeaderException: 
Required request header 'X-Sharer-User-Id' for method parameter type Long 
is present but converted to null
```

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
>      public UserDto createUser(@Valid @RequestBody final UserDto user) {
при попытке добавления дубля пользователя приходит ошибка 500, хотя ошбика на стороне клиента, должен быть код 4**

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
>      public UserDto updateUser(@Valid @RequestBody final UserDto user,
при попытке patch с некорректной почтой
```
curl --request PATCH \
  --url http://localhost:8080/users/1 \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "bob",
	"email": "1"
}'
```
приходит просто
```JSON
{
	"timestamp": "2024-05-05T11:11:31.203+00:00",
	"status": 400,
	"error": "Bad Request",
	"path": "/users/1"
}
```

но можно было бы вернуть причину ошибки

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      @GetMapping
По тз владелец еще должен видеть даты последнего и ближайшего следующего бронирования для каждой вещи.
Сейчас ответ приходит такой
```JSON
[
	{
		"id": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": {
			"id": 1,
			"bookerId": 3
		},
		"nextBooking": null,
		"comments": []
	},
	{
		"id": 2,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": []
	},
	{
		"id": 3,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": []
	}
]
```

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public State stateValidation(final String state) {
Можно сделать приватным

2024-05-05 11:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public void bookingExists(final long bookingId) {
Если метод не используется, можно убрать. Если будет использоваться, нужно поставить `@Override`

2024-05-06 06:44 UTC, PanCakeOFF31 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NotNull
Я почитал статью про валидацию оъектов.  Лучший вариант проводит валидацию на уровне сервисов. Но на данный момент оставлю на контроллерном слое через ...RequestDto... и использую готовую javax.validation.constraints.

2024-05-06 07:36 UTC, PanCakeOFF31 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingResponseDto> getAllBookingByUser(@RequestHeader("X-Sharer-User-Id") final long bookerId,
Аналогичено во всех других контроллерах такая фигня.

2024-05-06 07:41 UTC, PanCakeOFF31 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
>      public UserDto createUser(@Valid @RequestBody final UserDto user) {
Исправил на 409 - Conflict. В тестах допустимо было 500, поэтому нен стал менять.
![image](https://github.com/PanCakeOFF31/java-shareit/assets/92355670/97c58838-448c-495e-8a0f-ca8e2259656c)

2024-05-06 07:51 UTC, PanCakeOFF31 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      @GetMapping
![image](https://github.com/PanCakeOFF31/java-shareit/assets/92355670/d9283d61-2bcd-4431-9787-800d09f07352)

2024-05-06 18:26 UTC, z8q approved these changes

2024-05-06 18:26 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserResponseDto updateUser(@RequestBody final UserRequestDto user,
Тут, когда `@Valid` оставался, на некорректный email приходило
```JSON
{
	"error": "Ошибка валидации передаваемой сущности в теле запроса.",
	"description": "Поле/поля или значение поля/полей не соответствуют указанным ограничениям",
	"methodMessage": "Validation failed for argument [0] in public ru.practicum.shareit.user.dto.UserResponseDto ru.practicum.shareit.user.controller.UserController.updateUser(ru.practicum.shareit.user.dto.UserRequest to,long : [Field error in object 'userRequestDto' on field 'email': rejected value [1]; codes [Email.userRequestDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userRequestDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@718711d,.*]; default message [User.email - почта не соответствует шаблону @Email]] "
}
```

Сейчас просто 500 - непредвиденная ошибка

2024-05-07 07:16 UTC, PanCakeOFF31 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserResponseDto updateUser(@RequestBody final UserRequestDto user,
Упустил

2024-05-07 07:18 UTC, merged